### ISSUE TITLE
PanelGroup different height with collapsed children

### ISSUE THREAD

**Issue by fitterfizzle** [bvaughn/react-resizable-panels#306] opened 2024-02-22 16:19 UTC
I have a composition of 2 `<Panels/>` inside a `<PanelGroup/>`.

They are not rendered conditionally, but `<Panel/>` 1 on the left has the `collapsible` property defined. When `<Panel/>` 1 is collapsed to 0, the total height of `<PanelGroup/>` appears to be increasing by 15px (not empirical value, just based on current setup), but when opening the `<Panel/>` 1 then the size appears to go down to the expected height value, which is minus the 15px mentioned above.

Any ideas, help what the issue might be?

**Comment by bvaughn** [comment] 2024-02-22 16:59
This is most likely caused by some CSS/styling issue in your project. I can't really troubleshoot it without being able to see your code/styles.

**Comment by bvaughn** [comment] 2024-02-28 14:05
Closing because there isn't enough information here for me to do anything with this issue.

**Closed by bvaughn** 2024-02-28 14:05 UTC
Labels: needs information
