### ISSUE TITLE
Window resize collapses panels when using pixel sizing (prev issue continued)

### ISSUE THREAD

**Issue by psychedelicious** [bvaughn/react-resizable-panels#226] opened 2023-12-06 05:38 UTC
Previous issue:  #210

v63

The problem still occurs, but not immediately when on the first resize event.

https://app.replay.io/recording/unexpected-collapses-on-window-resize-w-pixels--787e207f-0524-48e3-b8f6-a0418ca98587

Also note that later on in the replay, the left panel expands and right panel collapses - same unexpected calculations.

Between the first and second passes in `validatePanelGroupLayout`, `remainingSize` ends up negative. I suppose this results in `resizePanel` deciding there isn't enough room and saying the new final size is 0. Maybe the pixel-constrained panels need first dibs on remaining space? I'm a bit lost, this deep in the logic.

**Comment by bvaughn** [comment] 2023-12-10 15:52
> Between the first and second passes in validatePanelGroupLayout, remainingSize ends up negative. I suppose this results in resizePanel deciding there isn't enough room and saying the new final size is 0. Maybe the pixel-constrained panels need first dibs on remaining space? I'm a bit lost, this deep in the logic.

It's possible this issue was being caused by a floating point precision issue. I've tried to better account for that by using `.toFixed` when distributing drag delta across a group of panels.

**Comment by bvaughn** [comment] 2023-12-10 16:25
I left a comment on the Replay.

**Comment by bvaughn** [comment] 2023-12-10 16:34
Going to close this issue since I don't plan to take action on it. Happy to continue talking here though.

**Closed by bvaughn** 2023-12-10 16:34 UTC
Labels: wontfix

**Comment by psychedelicious** [comment] 2023-12-11 02:17
Dropping support for pixel layouts is a bummer, but it sounds like the right choice for this library. Thanks for taking the time to try to make it work, and for making the choice to keep the library focused on what it can and does do well.

**Comment by bvaughn** [comment] 2023-12-11 02:19
Thank you so much for understanding 🙏🏼

**Comment by bvaughn** [comment] 2025-07-22 00:13
Adding this comment to a few older issues, but I am currently considering an idea (see https://github.com/bvaughn/react-resizable-panels/issues/496#issuecomment-3099991742) that might be useful in supporting pixel-based constraints. Just an FYI in case you have any thoughts about that direction.

(I know this is an old issue, so feel free to ignore this comment if you are no longer interested in this feature.)
