### ISSUE TITLE
Error while resize window using conditional panel with minSizePixels prop

### ISSUE THREAD

**Issue by anikesh-butler** [bvaughn/react-resizable-panels#229] opened 2023-12-08 16:43 UTC
### Console Error 
```
react-resizable-panels.browser.development.esm.js:1259 Uncaught Error: Invalid 2 panel layout: 100%
    at validatePanelGroupLayout (react-resizable-panels.browser.development.esm.js:1259:11)
    at ResizeObserver.<anonymous> (react-resizable-panels.browser.development.esm.js:1466:28)
```

### Steps to reproduce:
1. https://react-resizable-panels.vercel.app/examples/conditional, use more than one panel with condition 
2. Assign minSizePixels props value to each Panel
3. Try to resize window 

Sandbox link: https://codesandbox.io/p/sandbox/divine-surf-67cgdl?file=%2Fsrc%2FApp.js%3A34%2C60

**Comment by anikesh-butler** [comment] 2023-12-08 16:57
Sure @bvaughn, please have a look here https://www.loom.com/share/ca51c8704bb440c489e84309552dfde8?sid=9eae1ae0-a282-47e6-a1b9-2080c051dcc4

**Comment by anikesh-butler** [comment] 2023-12-08 16:59
Same issue exist with 2 panels also with the error message `Error: Invalid 2 panel layout: 100%`

**Comment by anikesh-butler** [comment] 2023-12-08 17:01
```javascript
export default function App() {
  const [showLeftPanel, setShowLeftPanel] = useState(false);

  useEffect(() => {
    setShowLeftPanel(true);
  }, []);

  return (
    <div className="App">
      <PanelGroup direction="horizontal">
        {showLeftPanel && (
          <>
            <Panel id="left" order={1} minSizePixels={10}>
              left
            </Panel>
            <PanelResizeHandle />
          </>
        )}
        <Panel id="center" order={2} minSizePixels={10}>
          middle
        </Panel>
      </PanelGroup>
    </div>
  );
}
```

@bvaughn you can try with this snippet. It looks like it's counting for newly added panels after first render.

**Comment by bvaughn** [comment] 2023-12-09 18:23
> Sure @bvaughn, please have a look here https://www.loom.com/share/ca51c8704bb440c489e84309552dfde8?sid=9eae1ae0-a282-47e6-a1b9-2080c051dcc4

Recording a Replay would be useful to diagnose the bug. Recording a Loom isn't, really, since I can't inspect what's happening in the library.

**Comment by anikesh-butler** [comment] 2023-12-11 12:35
> ```js
> export default function App() {
>   const [showLeftPanel, setShowLeftPanel] = useState(false);
> 
>   useEffect(() => {
>     setShowLeftPanel(true);
>   }, []);
> 
>   return (
>     <div className="App">
>       <PanelGroup direction="horizontal">
>         {showLeftPanel && (
>           <>
>             <Panel id="left" order={1} minSizePixels={10}>
>               left
>             </Panel>
>             <PanelResizeHandle />
>           </>
>         )}
>         <Panel id="center" order={2} minSizePixels={10}>
>           middle
>         </Panel>
>       </PanelGroup>
>     </div>
>   );
> }
> ```
> 
> @bvaughn you can try with this snippet. It looks like it's counting for newly added panels after first render.




@bvaughn please try this snippet to reproduce the issue.

**Comment by bvaughn** [comment] 2023-12-11 14:13
I'd rather have a **full repro** that I can just click and run rather than a snippet that I have to fill in context around.

I've converted this into a Code Sandbox here: https://codesandbox.io/p/sandbox/adoring-dew-s3jjg6

It does not reproduce the error you're describing.

**Comment by bvaughn** [comment] 2023-12-13 03:19
I've decided to remove support for pixel constraints from this library's v1.0.0 release (which I just published). It adds too many edge cases for me to support (especially considering that I don't need the functionality in any of my apps).

I am going to close this since it seems specific to pixel constraints. If you still see this behavior in the v1.0.0 release though, let's talk more.

**Closed by bvaughn** 2023-12-13 03:19 UTC
Labels: question

**Comment by bvaughn** [comment] 2023-12-13 14:18
Btw @anikesh-butler I think the issue you're reporting here _might_ have been caused by this: ab496d8259e6390b121b3f6555570b392af49e62

**Comment by jpainam** [comment] 2024-03-16 23:18
```typescript
Uncaught Error: Previous layout not found for panel index 2
    at assert (react-resizable-panels.browser.development.esm.js:658:11)
    at adjustLayoutByDelta (react-resizable-panels.browser.development.esm.js:820:7)
    at resizeHandler (react-resizable-panels.browser.development.esm.js:1986:26)
    at setResizeHandlerState (react-resizable-panels.browser.development.esm.js:2331:15)
    at eval (react-resizable-panels.browser.development.esm.js:651:5)
    at Set.forEach (<anonymous>)
    at updateResizeHandlerStates (react-resizable-panels.browser.development.esm.js:646:28)
    at HTMLBodyElement.handlePointerMove (react-resizable-panels.browser.development.esm.js:472:3)
app-index.js:33 Previous layout not found for panel index 2
window.console.error @ app-index.js:33
react-resizable-panels.browser.development.esm.js:658 Uncaught Error: Previous layout not found for panel index 2
    at assert (react-resizable-panels.browser.development.esm.js:658:11)
    at adjustLayoutByDelta (react-resizable-panels.browser.development.esm.js:820:7)
    at resizeHandler (react-resizable-panels.browser.development.esm.js:1986:26)
    at setResizeHandlerState (react-resizable-panels.browser.development.esm.js:2331:15)
    at eval (react-resizable-panels.browser.development.esm.js:651:5)
    at Set.forEach (<anonymous>)
    at updateResizeHandlerStates (react-resizable-panels.browser.development.esm.js:646:28)
    at HTMLBodyElement.handlePointerMove (react-resizable-panels.browser.development.esm.js:472:3)
app-index.js:33 Previous layout not found for panel index 2
```

I get this error when I click on the resize handle after using a conditional panel.
Somehow, the resize handle remains visible after i hide the panel index 2

**Comment by anikesh-butler** [comment] 2024-03-18 12:41
Thanks @bvaughn for notifying about this. I'll try to see if this fix the issue i was seeing.
