### ISSUE TITLE
Panels messes with click events in react-testing-library tests using JSDOM.

### ISSUE THREAD

**Issue by karl-run** [bvaughn/react-resizable-panels#398] opened 2024-08-30 06:07 UTC
I just discovered this, so I haven't made a minimal repro yet.

But I had this simple home-made two pane view that I could 1:1 replace with two `Panel` in a `PanelGroup` ([diff](https://github.com/navikt/syk-dig/commit/96ba2a202acba8ef1d86b9b8439f646f3b20d312#diff-7b9fa120f25e87b57a5a444e86e97e8b2b7ef22b02191b6e2ac5fb8695cdaf4e)) which was super nice!

But I have a couple of RTL+JSDOM tests that started failing on non-obvious stuff, like clicking a button using userEvent would be fine, it would find the button and click it, and whatever what supposed to happen after the button click didn't happen. Like the event didn't fire at all.

For example this test (big uggo test pls don't judge :sweat:) would fail on line 53: 

https://github.com/navikt/syk-dig/blob/main/src/components/nasjonal-oppgave/__tests__/submitOppgave.test.tsx#L52-L53

If I straight up replace all the `Panel` and `PanelGroup` with `div` the tests run again.

**Comment by bvaughn** [comment] 2024-08-30 12:23
Seems like a duplicate of #367. Check out this comment about styling: https://github.com/bvaughn/react-resizable-panels/issues/367#issuecomment-2241908486

**Comment by bvaughn** [comment] 2024-09-03 12:24
This seems most likely to be a duplicate so I'm going to close it for now.

**Closed by bvaughn** 2024-09-03 12:24 UTC
