### ISSUE TITLE
export "useId" was not found in "react"

### ISSUE THREAD

**Issue by jasonpaulmichel** [bvaughn/react-resizable-panels#82] opened 2023-01-12 20:49 UTC
**Please note**: This is related to Webpack issue: https://github.com/webpack/webpack/issues/14814

Some bundles (Webpack) may throw an error during compilation if code references a named import that a module does not export– even if the import is only used conditionally.

The error thrown by Webpack will look like:
```
export 'useId' (imported as '$fpI56$useId') was not found in 'react'
```

---

To work around this, the following change was made in 0.0.38:
```diff
- const useReactId = (React as any).useId as () => string;
+ // `toString()` prevents bundlers from trying to `import { useId } from 'react'`
+ const useReactId = (React as any)['useId'.toString()] as () => string;
```

Unfortunately it caused a regression and was reverted in 0.0.39. (Seemingly the new syntax confused Parcel.)

---

(Description modified by @bvaughn)

**Comment by bvaughn** [comment] 2023-01-12 20:51
Just a warning? Should be safe to ignore.

https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/hooks/useUniqueId.ts

**Comment by jasonpaulmichel** [comment] 2023-01-12 21:07
Damn, thank you for the fast response!

**Comment by bvaughn** [comment] 2023-01-12 21:11
No prob! Sorry for the confusion.

**Comment by javiernievas** [comment] 2023-02-17 21:00
I can confirm it raises an error on React v17. As it is trying to import useId and it does not exists.

ERROR in ./node_modules/react-resizable-panels/dist/react-resizable-panels.module.js 8:68-80  
export 'useId' (imported as '$jhddX$useId') was not found in 'react'

**Comment by bvaughn** [comment] 2023-02-20 02:50
Can you share a _repro_ for this? Same as I asked for with #104.

**Comment by brightloudnoise** [comment] 2023-04-01 04:49
Here is a [repro](https://github.com/brightloudnoise/react-rezizable-panels-useid-repro) using CRA and React v17, and a possible  [work-around](https://github.com/floating-ui/floating-ui/issues/1595#issuecomment-1082521810) for webpack.

Thanks!

**Comment by bvaughn** [comment] 2023-04-01 14:38
@brightloudnoise Thanks for the work around pointer.

```diff
- const useReactId = (React as any).useId as () => string;
+ // `toString()` prevents bundlers from trying to `import { useId } from 'react'`
+ const useReactId = (React as any)['useId'.toString()] as () => string;
```

That's some funky syntax!

I'm not opposed to adding it here, provided it doesn't break anything though.

**Comment by bvaughn** [comment] 2023-04-01 16:56
Thinking about this a little more and I worry this might cause tree shaking issues.

It seems like, ideally, this should be something that Webpack supports (https://github.com/webpack/webpack/issues/14814)

**Comment by bvaughn** [comment] 2023-04-01 17:08
Closed via ed96947

**Comment by bvaughn** [comment] 2023-04-02 03:42
Fixed in 0.0.38

**Comment by bvaughn** [comment] 2023-04-02 12:54
Looks like this change caused a regression (#118) so I'm going to revert it in 0.0.39 for now.

**Closed** 2023-04-02 14:16 UTC

**Comment by bvaughn** [comment] 2023-04-02 14:19
Should be fixed in 0.0.39

**Comment by brightloudnoise** [comment] 2023-04-02 18:31
Thanks for the fixes, and sorry the workaround caused other headaches.

**Comment by bvaughn** [comment] 2023-04-02 18:31
No worries 😄
