### ISSUE TITLE
Uncaught runtime errors: ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by seuristic** [bvaughn/react-resizable-panels#399] opened 2024-08-30 11:10 UTC
I have integrated the resizing panel library and encountering an issue with it. I have actually implemented from Shadcn docs manually, and after completing the setup, whenever I try moving resizing handle fast to the right, I am getting a runtime error saying: 

> Uncaught runtime errors: ResizeObserver loop completed with undelivered notifications.

Here are the screenshots of the issue that I have encountered:
![image](https://github.com/user-attachments/assets/827682c7-0ca1-429d-9292-ffe23ef9bd19)

Here are the code snippets:

Resizable.tsx file:

```typescript
import { GripVertical } from "lucide-react"
import * as ResizablePrimitive from "react-resizable-panels"

import { cn } from "core/lib/utils"

const ResizablePanelGroup = ({ className, ...props }: React.ComponentProps<typeof ResizablePrimitive.PanelGroup>) => (
  <ResizablePrimitive.PanelGroup
    className={cn("flex h-full w-full data-[panel-group-direction=vertical]:flex-col", className)}
    {...props}
  />
)

const ResizablePanel = ResizablePrimitive.Panel

const ResizableHandle = ({
  withHandle,
  className,
  ...props
}: React.ComponentProps<typeof ResizablePrimitive.PanelResizeHandle> & {
  withHandle?: boolean
}) => (
  <ResizablePrimitive.PanelResizeHandle
    className={cn(
      "relative flex w-px items-center justify-center bg-border after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring focus-visible:ring-offset-1 data-[panel-group-direction=vertical]:h-px data-[panel-group-direction=vertical]:w-full data-[panel-group-direction=vertical]:after:left-0 data-[panel-group-direction=vertical]:after:h-1 data-[panel-group-direction=vertical]:after:w-full data-[panel-group-direction=vertical]:after:-translate-y-1/2 data-[panel-group-direction=vertical]:after:translate-x-0 [&[data-panel-group-direction=vertical]>div]:rotate-90",
      className
    )}
    {...props}
  >
    {withHandle && (
      <div className="z-10 flex h-4 w-3 items-center justify-center rounded-sm border bg-border">
        <GripVertical className="h-2.5 w-2.5" />
      </div>
    )}
  </ResizablePrimitive.PanelResizeHandle>
)

export { ResizablePanelGroup, ResizablePanel, ResizableHandle }
```

Usage:
![image](https://github.com/user-attachments/assets/ea572eb6-c6a2-4959-a42e-6e52bcb67901)

**Comment by bvaughn** [comment] 2024-08-30 12:24
Code snippets and screenshots aren’t going to be enough for me to help. Please share a complete runnable reproduction of the issue you’re reporting

**Comment by bvaughn** [comment] 2024-09-03 12:24
Closing because this isn't actionable with the info provided.

**Closed by bvaughn** 2024-09-03 12:24 UTC
